// Generated by CoffeeScript 1.9.3
(function() {
  var Entries, StockList, api, express;

  express = require('express');

  api = express.Router();

  StockList = require('../models/StockList');

  Entries = require('../models/Entries');

  api.get('/api/stockList', function(req, res) {
    return StockList.getStockListOrdered().then(function(stockList) {
      return res.json(stockList);
    });
  });

  api["delete"]('/api/stockList', function(req, res) {
    var stockName;
    stockName = req.query.stockName;
    return StockList.deleteStockWithName(stockName).then(function() {
      return Entries.deleteAllEntriesForStockWithName(stockName).then(function() {
        return res.sendStatus(200);
      });
    });
  });

  api.get('/api/stockList/stockExists', function(req, res) {
    var stock;
    stock = JSON.parse(req.query.stock);
    return StockList.doesStockWithNameExist(stock.stockName.toUpperCase()).then(function(stockExists) {
      return res.json(stockExists);
    });
  });

  api.post('/api/stockList/add', function(req, res) {
    var stock;
    stock = JSON.parse(req.query.stock);
    stock.stockName = stock.stockName.replace(' ', '_').toUpperCase();
    if (!stock.number) {
      stock.number = 0;
    }
    if (!stock.number) {
      stock.acb = 0;
    }
    return StockList.addStock(stock).then(function() {
      return res.sendStatus(200);
    });
  });

  api.get('/api/entriesList', function(req, res) {
    return Entries.getAllEntriesOrdered().then(function(entriesList) {
      return res.json(entriesList);
    });
  });

  module.exports = api;

}).call(this);
