// Generated by CoffeeScript 1.9.3
(function() {
  var Entries, StockList, api, controller, express, stockController;

  express = require('express');

  controller = express.Router();

  stockController = require('./stock');

  api = require('./api');

  Entries = require('../models/Entries');

  StockList = require('../models/StockList');

  controller.use(stockController);

  controller.use(api);

  controller.get('/stocklist', function(req, res) {
    return res.render('stocklist', {
      title: 'Stock List'
    });
  });

  controller.get('/debug', function(req, res) {
    return res.render('debug', {
      title: 'Debug'
    });
  });

  controller.get('*', function(req, res) {
    return res.render('index', {
      title: 'Stock Application'
    });
  });

  module.exports = controller;

}).call(this);
