// Generated by CoffeeScript 1.9.3
(function() {
  var Entries, StockList, api, express, router, stockController;

  express = require('express');

  router = express.Router();

  stockController = require('./stock');

  api = require('./api');

  Entries = require('../models/Entries');

  StockList = require('../models/StockList');

  router.use(stockController);

  router.use(api);

  router.get('/stocklist', function(req, res) {
    return res.render('stocklist', {
      title: 'Stock List'
    });
  });

  router.get('/debug', function(req, res) {
    return res.render('debug', {
      title: 'Debug'
    });
  });

  router.get('*', function(req, res) {
    return res.render('index', {
      title: 'Stock Application'
    });
  });

  module.exports = router;

}).call(this);
