// Generated by CoffeeScript 1.9.3
(function() {
  var Entries, StockList, controller, express;

  express = require('express');

  controller = express.Router();

  StockList = require('../models/StockList');

  Entries = require('../models/Entries');

  controller.get('/stocklist', function(req, res) {
    var options;
    options = {
      title: 'Stock List',
      liveEditStock: req.session.liveEditStock ? req.session.liveEditStock : void 0
    };
    req.session.liveEditStock = null;
    return res.render('stocklist', options);
  });

  controller.post('/addstock', function(req, res) {
    var stock;
    stock = req.body;
    return StockList.doesStockWithNameExist(stock.stockName.toUpperCase()).then(function(stockExists) {
      if (stockExists) {
        req.session.liveEditStock = stock;
        return res.redirect('/stocklist');
      } else {
        stock.stockName = stock.stockName.toUpperCase();
        if (!stock.number) {
          stock.number = 0;
        }
        if (!stock.acb) {
          stock.acb = 0;
        }
        StockList.addStock(stock);
        return res.redirect('/stocklist');
      }
    });
  });

  module.exports = controller;

}).call(this);
