// Generated by CoffeeScript 1.9.3
(function() {
  var Entries, cleanEntry, db, entriesTable;

  db = require('../utilities/DB');

  entriesTable = db.get('entries');

  Entries = {
    deleteAllEntriesForStockWithName: function(stockName) {
      return entriesTable.remove({
        stockName: stockName
      }, function(err) {
        if (err) {
          throw err;
        }
      });
    },
    getAllEntriesOrdered: function() {
      return entriesTable.find({}, {
        sort: {
          stockName: 1,
          year: 1,
          month: 1,
          day: 1,
          tradeNumber: 1
        }
      }, function(err, entries) {
        if (err) {
          throw err;
        }
        return entries;
      });
    },
    getEntriesForStockOrdered: function(stockName) {
      return entriesTable.find({
        stockName: stockName
      }, {
        sort: {
          year: 1,
          month: 1,
          day: 1,
          tradeNumber: 1
        }
      }, function(err, entries) {
        if (err) {
          throw err;
        }
        return entries;
      });
    },
    removeEntryById: function(_id) {
      return entriesTable.remove({
        _id: _id
      }, function(err) {
        if (err) {
          throw err;
        }
      });
    },
    addEntry: function(entry) {
      entry = cleanEntry(entry);
      return entriesTable.insert(entry);
    },
    updateEntry: function(entry) {
      entry = cleanEntry(entry);
      return entriesTable.update({
        _id: entry._id
      }, entry, function(err) {
        if (err) {
          throw err;
        }
      });
    }
  };

  module.exports = Entries;

  cleanEntry = function(entry) {
    entry.year = +entry.year;
    entry.month = +entry.month;
    entry.day = +entry.day;
    entry.tradeNumber = +entry.tradeNumber;
    return entry;
  };

}).call(this);
