// Generated by CoffeeScript 1.9.3
(function() {
  var Stocks, db, sanitizeStock, stocksTable;

  db = require('../utilities/DB');

  stocksTable = db.get('stocks');

  Stocks = {
    getStocks: function() {
      return stocksTable.find({}, function(err, stocks) {
        if (err) {
          throw err;
        }
        return stocks;
      });
    },
    getStockByName: function(stockName) {
      return stocksTable.findOne({
        stockName: stockName
      }, function(err, initialValues) {
        if (err) {
          throw err;
        }
        return initialValues;
      });
    },
    doesStockWithNameExist: function(stockName) {
      return stocksTable.count({
        'stockName': stockName
      }).then(function(count) {
        return count !== 0;
      });
    },
    addStock: function(stock) {
      stock = sanitizeStock(stock);
      return stocksTable.insert(stock);
    },
    deleteStockWithName: function(stockName) {
      return stocksTable.remove({
        stockName: stockName
      });
    }
  };

  module.exports = Stocks;

  sanitizeStock = function(stock) {
    return {
      stockName: stock.stockName,
      number: stock.number,
      acb: stock.acb
    };
  };

}).call(this);
